"""empty message

Revision ID: 0aa55f48143b
Revises: c27cea255196
Create Date: 2025-01-10 19:39:07.425250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa55f48143b'
down_revision = 'c27cea255196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_from_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_to_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_from_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_to_id'], ['id'])
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_to_id')
        batch_op.drop_column('user_from_id')

    # ### end Alembic commands ###
