"""empty message

Revision ID: 14ccf8dd26f7
Revises: db302410657b
Create Date: 2025-01-18 08:58:05.029233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14ccf8dd26f7'
down_revision = 'db302410657b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('image')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
