"""empty message

Revision ID: f09af522cc9c
Revises: 0aa55f48143b
Create Date: 2025-01-10 20:10:53.616047

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f09af522cc9c'
down_revision = '0aa55f48143b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('ADMIN', 'CLIENT', 'PROFESSIONAL', name='myenum'),
               type_=sa.Enum('ADMIN', 'CLIENT', 'PROFESSIONAL', name='use_role_enum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('ADMIN', 'CLIENT', 'PROFESSIONAL', name='use_role_enum'),
               type_=postgresql.ENUM('ADMIN', 'CLIENT', 'PROFESSIONAL', name='myenum'),
               existing_nullable=False)

    # ### end Alembic commands ###
